name: good_grandma
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.8+29
#安卓混淆打包代码 flutter build apk --no-shrink

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # 网络请求库
  dio: ^4.0.0
  # 状态管理
  provider: ^5.0.0
  # 弹出toast吐司
  fluttertoast: ^8.0.8
  # 选择器
  flutter_picker: ^2.0.2
  # 相机相册
  image_picker: ^0.8.3+2
  # 相册
  image_picker_for_web: ^2.1.2
  # 日期
  date_format: ^2.0.4
  # 持久化工具
  get_storage: ^2.0.3
  #日历
  table_calendar: ^3.0.2
  # 国际化处理
  intl: ^0.17.0
  # 图片缓存
  cached_network_image: ^3.1.0
  # 查看大图
  extended_image: ^4.1.0
  # 高德定位
  amap_flutter_location: ^2.0.0
  # 高德地图
  amap_flutter_map: ^2.0.2
  # 申请权限
  permission_handler: ^8.1.4+2
  # MD5加密
  crypto: ^3.0.1
  # 保存图片到相册
  image_gallery_saver: ^1.7.1
  # 打开系统设置
  app_settings: ^4.1.1
  # 查看图片视图view
  photo_view: ^0.12.0
  # 签名
  signature: ^4.1.1
  # 图表
  fl_chart: ^0.40.0
  # 应用信息
  package_info: ^2.0.2
  # 文件选择器
#  file_picker: ^4.0.2
  # 阅读文档
  flutter_filereader: ^3.0.0
  # 刷新
  flutter_easyrefresh: ^2.2.1
  # 加载网页
  flutter_html: ^2.1.2
  # 打开链接
  url_launcher: ^6.0.10
  #用于在文件系统上查找常用位置
  path_provider: ^2.0.4
  #二维码/条形码扫描插件
  barcode_scan: ^3.0.1
  #webview
  webview_flutter: ^2.0.0
  #获取设备IMEI
  device_info: ^2.0.3
  #鲁班压缩
  flutter_luban: ^0.1.13
  #角标
  badges: ^2.0.1
  #带进度条提示加载框
  flutter_easyloading: ^3.0.3
  #相机
  camera: ^0.9.4+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 基于dio的网络请求日志
  dio_log : ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
